### ISSUE TITLE
Aren't these icons inverted?

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-icon-theme#101]
Hello, guys. What's up?

Today, I noticed something that might be a little bug, I don't know. Take a look at the screenshot, please:

![drives](https://cloud.githubusercontent.com/assets/7181488/2631131/f531bddc-be54-11e3-8b98-754f1ec3d2f1.png)

As you can see in the picture, the first icon shows a red flash drive (if I'm not wrong), but it is actually my USB external 500 GB HDD; and the last icon shows a kind of a hard drive, but it is actually my USB SanDisk 8 GB flash drive. So... aren't those icons inverted?

I hadn't noticed this before because, since the day I started using Numix Icon Theme Circle, I've been using my flash drive only, and not my external HDD. And I thought that HDD icon would go with all removable media, so I didn't care. Then, today, when I plugged in my HDD, I noticed that red flash drive icon.

So, is that a bug?

Thanks for your time, guys. :)

brunces

**Comment by wa4557** [comment]
What do you think about this one?
![test](https://cloud.githubusercontent.com/assets/6475757/7445898/18621234-f1c6-11e4-8e11-0565fa766136.png)

**Comment by dirtydancing** [comment]
Looking good! :)  Maybe make the USB symbol darker and "mutli-coloured" in the style of `harddrive.svg`? On the other hand, this should be readily distinguishable from `harddrive.svg`. Possibly use the red colour of the USB stick also for the USB harddrive, consistent for "USB"?

![harddrive](https://cloud.githubusercontent.com/assets/7164227/7446049/8573efaa-f1cb-11e4-9bab-224cfdedb3b9.png)

**Comment by Foggalong** [comment]
Spoke to @me4oslav and he says to use the `harddrive.svg` icon but with the red USB colour as @dirtydancing said :)

**Comment by wa4557** [comment]
so like this?
![drive-harddisk-usb](https://cloud.githubusercontent.com/assets/6475757/7446403/8e4f8c22-f1d7-11e4-9091-49db5f850832.png)

**Comment by me4oslav** [comment]
Not just the red colour. Look at how more detailed the symbol on normal HDD
icon looks like because it is multi coloured. With white USB on red
background it looks too plain.

**Comment by dirtydancing** [comment]
In the following, I will go through a couple of options and make a recommendation.

Continuing from above, how about s.th. like this (48x48 enlarged, original size below)?

1)
![proposed](https://cloud.githubusercontent.com/assets/7164227/7539661/bfe1efe4-f5a8-11e4-8e89-c5e964054182.png)

![proposed_48x48](https://cloud.githubusercontent.com/assets/7164227/7539664/c29f154a-f5a8-11e4-9ef3-d55331298941.png)

The icons above are using `#f0f0f0` as the lightest colour. In contrast, this is how this icon turns out when the dark colour `#073642` from `harddrive.svg` is used instead. I think I prefer the light colour.

2)
![proposed_dark](https://cloud.githubusercontent.com/assets/7164227/7539832/05e20d8e-f5aa-11e4-9771-e6223322e6c6.png)

![proposed_dark_48x48](https://cloud.githubusercontent.com/assets/7164227/7539839/14e9882a-f5aa-11e4-85e7-294d48432347.png)

Another alternative would be to simply use `harddrive.svg` with the red colour. Here are dark and light variants for that:

3)
![proposed2_dark](https://cloud.githubusercontent.com/assets/7164227/7540047/c5b2b202-f5ab-11e4-99fd-c2119a4a45d1.png)

4)
![proposed2_light](https://cloud.githubusercontent.com/assets/7164227/7540051/c85fd1e2-f5ab-11e4-9d03-3ea50f1b918c.png)

Given these options, I think I would go for the last one, option 4), `harddrive.svg` with red colour and light colours in the front.

Reasons:

a) That one is sufficiently distinguished from `harddrive.svg` (cf. comparison below).

![harddrive](https://cloud.githubusercontent.com/assets/7164227/7540172/b5c59570-f5ac-11e4-9c69-445616347750.png)
![proposed2_light](https://cloud.githubusercontent.com/assets/7164227/7540176/b8a8660a-f5ac-11e4-834f-321dc4a0d7ac.png)

b) In addition, from a visual standpoint, the harddrive symbol scales better than the USB symbol, it is better visible.

c) Finally, the USB stick symbol does not use the USB symbol, so it might even be confusing if the USB harddrive contains the USB symbol (the USB harddrive might actually be mistaken for a USB stick).

With option 4), this would lead to these two icons for USB media:

![usb](https://cloud.githubusercontent.com/assets/7164227/7540206/03a79428-f5ad-11e4-9b44-2360913a7015.png)
![proposed2_light](https://cloud.githubusercontent.com/assets/7164227/7540213/0baaeaa8-f5ad-11e4-9979-2859ccd860d3.png)

What do you make of this?

**Comment by Foggalong** [comment]
@dirtydancing checked with @me4oslav and we're both leaning toward [style 3](https://cloud.githubusercontent.com/assets/7164227/7540047/c5b2b202-f5ab-11e4-99fd-c2119a4a45d1.png) so if you set up a pull request I'll merge it in :)

**Comment by Foggalong** [comment]
@dirtydancing checked with @me4oslav and we're both leaning toward [style 3](https://cloud.githubusercontent.com/assets/7164227/7540047/c5b2b202-f5ab-11e4-99fd-c2119a4a45d1.png) so if you set up a pull request I'll merge it in :)

**Comment by dirtydancing** [comment]
Sure thing, style 3 it be, will do :)

One question: at the moment, these are these 4 USB media icons in Numix base:

![usb](https://cloud.githubusercontent.com/assets/7164227/7599278/ed33a2b6-f900-11e4-9ed7-30a721bc9776.png)

`drive-harddisk-usb.svg` will be the red harddisk (symbol change compared to the present state)

`drive-removable-media-usb.svg` will be the usb stick (just like at present, only an icon file instead of a symlink)

How about `drive-removable-media.svg` and `drive-removable-media-ieee1394.svg`?

Am I correct in assuming that the latter two should be symlinks with the target `drive-removable-media-usb.svg`? (which means the USB stick symbol, just like at present)

I am asking because in sizes 64x64 and larger, these icons look currently look like this:

![usb2](https://cloud.githubusercontent.com/assets/7164227/7599478/a6baa36e-f902-11e4-90d9-2198eca5b472.png)

This would mean that `drive-removable-media.svg` and `drive-removable-media-ieee1394.svg` should rather be the harddrive symbol than the USB stick symbol?

Or does this mean that those two icons should actually be the grey harddisk symbol in the sizes up to 48x48?

Please let me know, and I will submit the pull request accordingly.

Alas, actually there are also a couple of further symlinks, presently all pointing to the target `drive-harddisk-usb.svg` (up to size 48x48). Probably will need to go through these and decide which symbol is appropriate. I will take a closer look at this tomorrow and see what I can come up with.

**Comment by dirtydancing** [comment]
Adding a separate device icon for a USB harddrive is turning out to be more complex than anticipated.

First, visually, with style 3, there is a potential problem: usually the colour red is used for warning purposes and for indicating a certain status (not for a "neutral" device). For the USB stick on its own, that is currently OK because that is the only USB stick icon. A problem arises for USB harddrive when there is the grey harddrive icon and the also additionally the red one: users might mistake this for some kind of "harddrive warning".

To demonstrate, here are two screenshots of the grey and the intended red (USB) harddrive:

![grey](https://cloud.githubusercontent.com/assets/7164227/7616099/56479c02-f9a2-11e4-86e4-68ae67730da1.png)
![red](https://cloud.githubusercontent.com/assets/7164227/7616102/5a48b070-f9a2-11e4-8550-4bc8d50e477a.png)

Second, there are several further symlinks with the target `drive-harddisk-usb.svg` in the fixed sizes up to `48x48`. These are:

`drive-removable-media.svg`
`drive-removable-media-ieee1394.svg`
`drive-removable-media-usb.svg`
`gnome-dev-flashdisk.svg`
`gnome-dev-flashkey.svg`
`gnome-dev-harddisk-usb.svg`
`gnome-dev-removable.svg`
`gnome-dev-removable-usb.svg`
`gnome-dev-unknown-usb.svg`
`media-removable.svg`
`usbpendrive_unmount.svg`
`usbpendrive-unmount.svg`

Not all of these names are completely straightforward to identify as either (USB) stick or (USB) harddisk, at least to me. And as I do not know how to test these, this is as far as I can take this issue for now.

Arguably, the only icon to keep the USB stick symbol could be `drive-removable-media-usb.svg`, with all the other icons changing to the "red harddrive" symbol, but that would be a pretty massive change (?).

Anyways, if someone would like to pick it up from here, please feel free to do so.

Currently, nothing appears to be broken, and imo the red USB stick symbol on its own is just fine.

Alternatively, it might be an idea to just change the red colour of the current USB symbol into a grey one similar to the harddrive grey. That way, all the media icons would be somewhat more consistent as device icons (not status icons). Another "neutral" colour that might allow for an additional harddrive device colour would be blue, but for a blue USB stick that might be confused with the blue `battery.svg`.

**Comment by Foggalong** [comment]
Don't worry about the colouring of the drive, we have a seperate warning icon for that sort of stuff. If we get complaints down the line we can always tweak things :)

**Comment by Foggalong** [comment]
@dirtydancing Could you setup a merge for the red version of the drive but use a name not used by any other device icon. That way whoever picks up this issue to try and find which icons need changing can use the icon already made by you for it :)

**Comment by dirtydancing** [comment]
Done :) Named `drive-harddisk-usb_alternative.svg`. Cf. https://github.com/numixproject/numix-icon-theme/pull/488

**Comment by Foggalong** [comment]
Thanks!
