### ISSUE TITLE
Icon for "Computer charging?"

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme#1013]
I've encountered an interesting situation when I plugged in an iPad to my laptop running Ubuntu 15.10 via USB the other day as it began charging and replacing the usually battery icon with a question mark.
Here are the screenshots:
![screenshot from 2016-02-13 11-37-38](https://cloud.githubusercontent.com/assets/6375934/13142283/cfe09774-d644-11e5-9564-ebb0cda7ec94.png)
![screenshot from 2016-02-13 11-35-04](https://cloud.githubusercontent.com/assets/6375934/13142294/dfd3a8b0-d644-11e5-8ba8-eb08c32169af.png)
Perhaps it might also be helpful to report that the question mark was replaced with a regular battery icon when iPad was fully charged, and that I don't have any icon theme without this problem.

**Comment by Foggalong** [comment]
@dirtydancing where does this fit into the battery system?

**Comment by dirtydancing** [comment]
Not sure what is going on here. Apparently, this is limited to iPads and working correctly on desktops? And apparently this issue it not limited to Numix icon theme, but occurs in all other icon themes as well?

@Sadi58 There is an overview of the Numix icon theme battery icon names over at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-98399311. Maybe this is of help to you? One thought that comes to mind is that maybe for iPads, Ubuntu is using fixed size 16 battery icons, whereas for the desktop, Ubuntu is using fixed size 22 icons? Just an idea.

**Comment by Sadi58** [comment]
If icon theme experts here don't have any idea, then this might well be at least Unity or Gnome bug -- considering (1) there is no missing battery icon in fixed size 16 or 22 status icons, and (2) we can see a battery-fully-charged-icon when iPad reaches fully charged status.
It seems I should also raise this issue as a bug at Ubuntu launchpad.

**Comment by dirtydancing** [comment]
With Arch/GNOME, I am having no difficulties at all, so this does not look like a GNOME bug to me.

Another angle to this: what could be a problem here is that Ubuntu/Unity is using battery icons from the `scalable` directory for iPads, in contrast from the fixed size 22 directory for desktops, but with the icon names being the same. And because e.g. there is `battery-full-charged-symbolic` in `scalable`, but there are not the numerical percentage named icons in `scalable`, this could lead to problems.

You could try and copy the percentage-named battery icons (such as `battery-080-charging`) from fixed size 16 to the `scalable` directory and see if that works (usually the icons in `scalable` are `symbolic`-named).

Anyways, it seems somewhat strange to me that Ubuntu/Unity would use different directories (or different battery icon names) for desktops and iPads, but then again this might be on purpose so that Ubuntu/Unity runs fine and adaptable on any device (?).

**Comment by dirtydancing** [comment]
@Sadi58 Ah, one more thought: are you by any chance using Unity's display scaling on the iPad? This might lead to Unity using battery icons from the `scalable` directory. If so, please check withouth display scaling.

**Comment by Sadi58** [comment]
@dirtydancing Thank you, but it seems there is some misunderstanding here; I have Ubuntu 15.10 installed on my laptop and I'm just plugging in my wife's iPad (with iOS 9.2.1 on it) to transfer files and/or make use its 3G internet connection, and iPad automatically starts charging from my laptop as well, thereby resulting in this "missing battery icon" problem.

Also, I copied all missing battery icons from 22 to 16, and then to scalable with no effect.

**Comment by dirtydancing** [comment]
I see, and yeah, that was a misunderstanding :) Well, in this case, because this issue exists with all icon themes, this might be an Ubuntu/Unity related issue indeed. I have not come across your scenario so far.

**Comment by wa4557** [comment]
@Sadi58 Is there any icon theme that shows these icons correctly (oxygen, breeze maybe). I guess there is an icon missing like `battery-computer-*` or something similar. But without knowing where to look it's a bit hard to find out which icon is missing :)

**Comment by Sadi58** [comment]
@wa4557 Considering that the problem exists in Ubuntu's default theme as well as all others, I've reported this as a Unity bug, and then noticed that it was already reported here: https://bugs.launchpad.net/ubuntu/+source/indicator-power/+bug/1470080
They say it's been fixed it, but I've just seen the same problem when I plugged in iPad that's not fully charged.
On the other hand I think this issue can be closed here as it seems Ubuntu folks have confirmed it's a Unity bug.
