### ISSUE TITLE
apt-get update results in a 404 Not Found error

### ISSUE THREAD

**Issue by SamusAranX** [numixproject/numix-icon-theme#1019]
Well, yeah.
I did all this:

    sudo add-apt-repository ppa:numix/ppa
    sudo apt-get update
    sudo apt-get install numix-icon-theme

but the last step results in this:
> W: Failed to fetch http://ppa.launchpad.net/numix/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages 404 Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.`

I'm on Debian 8.3 and my version of `add-apt-repository` came from the `software-properties-common` package.
Also, is there another way to install these icons? Up to now I've always relied on Debian's apt magic for themes and icons.

**Comment by Foggalong** [comment]
Oh cool, I didn't realise that Debian could use PPAs. @PaoloRotolo, any idea what the problem is?

The other way to install is to [download it](https://github.com/numixproject/numix-icon-theme/archive/master.zip) and then move the `Numix` and `Numix-Light` folders to the `/usr/share/icons/` directory.

**Comment by khurshid-alam** [comment]
This was fixed long ago.

**Comment by BoulderWu** [comment]
so what as the fix? lol
