### ISSUE TITLE
Gnome-Foot on budgie-desktop

### ISSUE THREAD

**Issue by fossfreedom** [numixproject/numix-icon-theme#1046]
![](http://pix.toile-libre.org/upload/original/1459630350.png)

The Gnome-Foot icon for the start menu button (top left) - was this intentional or is this a missing icon?

**Comment by bil-elmoussaoui** [comment]
For the gnome foot icon, i think it's a missing icon! can you provide the icon name?

**Comment by fossfreedom** [comment]
its "start-here-symbolic" - https://github.com/solus-project/budgie-desktop/commit/39694636f7969c39a8d47c81ee11e7ef456e3b32

**Comment by bil-elmoussaoui** [comment]
What do you think about a symlink to `view-compact-symbolic` or `view-grid-symbolic`?

**Comment by fossfreedom** [comment]
given that solus dumped view-grid for the circle on 'Faba' because (according to the commit) "its ugly" ... maybe not?

**Comment by Foggalong** [comment]
@fossfreedom Could you split the GNOME foot into a separate issue? It's likely that will be felt with separately from the battery problems (which I'm guessing will be a pain to solve)

**Comment by dirtydancing** [comment]
@fossfreedom Relating to the battery icon issue (which would indeed better be a separate issue):

Please cf. the battery icon overview over at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-98399311. The problem with the big battery icon could be caused by a  "symbolic" icon without padding being used instead of a bigger fixed size icon with padding, and then the battery icon without padding is scaled to the fixed size and thus looks bigger than the other icons.

When opening the new issue, it would be helpful to indicate what the battery icon name is, whether this size issue exists for fully charged and/or charging and/or discharging, and possibly what scalabe/fixed size icons are regularly used in the top bar of budgie-desktop.

**Comment by HEXcube** [comment]
Budgie uses the `start-here-symbolic` icon by default, as defined in _gsettings_ https://github.com/solus-project/budgie-desktop/blob/master/panel/applets/budgie-menu/com.solus-project.budgie-menu.gschema.xml . It contains this section:

```XML
<key type="s" name="menu-icon">
  <default>'start-here-symbolic'</default>
  <summary>Menu button icon</summary>
  <description>The icon to display on the main menu button</description>
</key>
```

What is normally displayed in Solus is the `start-here-symbolic` from **Faba** (the base icons for Solus default theme **Moka**). See https://github.com/moka-project/faba-icon-theme/blob/master/Faba/symbolic/places/start-here-symbolic.svg . Since **Numix** doesn't have one, it falls back to the GNOME's `start-here-symbolic` from **Adwaita**: https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/places/start-here-symbolic.svg .

So, I think Numix should also provide a symbolic version of the already existing `start-here` icon: https://github.com/numixproject/numix-icon-theme/blob/master/Numix/16/places/start-here.svg :relaxed:

**Comment by HEXcube** [comment]
@wa4557 Wow! That was quick! :smile: Thanx for the new symbolic icons. :relaxed:
