### ISSUE TITLE
Big Battery Status Icon

### ISSUE THREAD

**Issue by angelolev** [numixproject/numix-icon-theme#107]
I am using elementary os luna and when i installed this theme, i got a huge battery icon, how can i fix it? thanks

![icon](http://imgur.com/2O5FPk6)

**Comment by fselem** [comment]
@dirtydancing I recently installed the second beta for elementary os Freya, and the issue seems to be completely resolved.

![screenshot from 2015-02-12 03 26 18](https://cloud.githubusercontent.com/assets/7390659/6164007/9b63743c-b267-11e4-9374-453e3c9ca12b.png)

![screenshot from 2015-02-12 03 27 09](https://cloud.githubusercontent.com/assets/7390659/6164008/a19910dc-b267-11e4-972a-f1b1e64868f8.png)

Also, check out the new Beta 2 I was talking about http://beta.elementaryos.org

**Comment by dirtydancing** [comment]
@fselem Great! Thanks for your feedback. I shortly did check Freya Beta 2 after it was released, and I did not experience any battery icon size issues either.

Not relating to the battery icon size, just to let you know: One other thing I noticed is that the colour of the "fully-charged" battery icon is somewhat lighter with the default GTK theme (cf. your first screenshot), but e.g. with Numix GTK theme corresponds to the colour of the other indicator icons.

**Comment by dirtydancing** [comment]
@fselem PS: I just checked the battery icon colour again, and it is whiter not only for fully-charged, but also for charging (not for discharging, though, as seen in your second screenshot above). Again, with the default elementary GTK theme, not e.g. with Numix GTK theme. This appears to be related to the primary use of "symbolic"-named battery status icons for fully-charged and for charging (but not for discharging) in Ubuntu 14.04 LTS, which Freya is based on, and this seems to be a GTK theme issue.

No issues with the battery status icon size.

Comparative screenshots (battery charging):

Default elementary GTK theme:
![elementary_gtk](https://cloud.githubusercontent.com/assets/7164227/6164932/0038fbc0-b2a4-11e4-9834-78ff286c928d.png)

Numix GTK theme:
![numix_gtk](https://cloud.githubusercontent.com/assets/7164227/6164935/084cfd2a-b2a4-11e4-893e-8e8da94ac3f7.png)

**Comment by dirtydancing** [comment]
In addition, for comparison here are two screenshots of current Xubuntu 14.10. Battery status icon size is all fine (here: fully-charged), as already discussed, but with Xubuntu 14.10 also the battery status icon colour is all fine with the default Greybird GTK theme as well as with Numix GTK theme. Screenshots:

Default Greybird GTK theme (all fine):
![greybird_gtk](https://cloud.githubusercontent.com/assets/7164227/6165874/9b421528-b2ab-11e4-8bc0-dd96592425da.png)

Numix GTK theme (all fine):
![numix_gtk](https://cloud.githubusercontent.com/assets/7164227/6165877/a30c7b86-b2ab-11e4-8070-3e79c5ffa93b.png)

**Comment by fselem** [comment]
@dirtydancing You're quite right; I did not notice the color change initially. I checked to see if this was the case in Luna, and found that while the charged battery icon in an untouched state's color was consistent with the other icons, once it was clicked on it differed from the others, even though the other icons don't display the same behavior once clicked on.

![image](https://cloud.githubusercontent.com/assets/7390659/6170417/9f465476-b2a2-11e4-8ec3-b0f9cbfd09da.png)

As you can see, the colors are the same, but this is what happens when you click on the charged battery icon:

![screenshot from 2015-02-12 10 35 38](https://cloud.githubusercontent.com/assets/7390659/6170606/b7a4effe-b2a3-11e4-8909-bbe19ce05de4.png)

The color changes. Seemingly like it should (at first). But then once you click on other icons, the colors remain constant:

![screenshot from 2015-02-12 10 43 48](https://cloud.githubusercontent.com/assets/7390659/6170661/1b0cef2e-b2a4-11e4-88e0-4ac23122f1fc.png)

I figure this is probably an issue where the other icons aren't generating the correct event response, as  a color-change response seems like preferable behavior in this case.

**Comment by dirtydancing** [comment]
@fselem Not sure about the colour-change response, as e.g. in Ubuntu and Xubuntu the colour of the status icons does not change either, but definitely this is an issue of consistency. If you would like to take this further, s.th. to do at this point might be to file a "colour" bug report against elementary GTK theme.

**Comment by dirtydancing** [comment]
Regarding elementary OS: Just referencing this issue https://github.com/mank319/elementaryPlus/issues/17 which confirms that elementary OS Freya is using a 24x24 canvas on wingpanel (actual icon size is up to the icon theme).

At the same time, this confirms that for the battery status icons in Numix Base, the "symbolic"-symlinks in 24x24 are of relevance (for elementary OS and for Xubuntu, in contrast for Ubuntu it is the 22x22 ones).

**Comment by Foggalong** [comment]
I'm not quite sure what that means for this issue? We already cover 22px, 24px and symbolics for both.

**Comment by dirtydancing** [comment]
No new meaning for this issue, all is already covered indeed.

I just referenced this as background info and for clarification. The panel canvas sizes have been changing (not in Ubuntu, though, still 22x22), and that effects how the battery status icon is displayed.

**Comment by dirtydancing** [comment]
Just to avoid any more confusion: in the specific case of the battery status icon, it is important to be aware of the exact canvas size because of the "big battery status icon" problem.

Typically, a default icon theme containing fixed size battery icons will not additionally contain battery status icons in a "scalable" status directory. So by e.g. when displaying a 22x22 "fixed size" icon on a 24x24 canvas, the icon might just get a little blurry.

In contrast, because Numix Base also caters to GNOME distributions, in Numix Base there is also a "scalable" status directory (cf. discussion above). And depending on the distribution, the distribution might look into "scalable" if the exact canvas "fixed size" icon is not present, and by taking the icon from "scalable", we then arrive at the "big battery status icon" situation. This is because in "scalable", there is a 16x16 canvas and a 16px actual icon size as well as a somewhat different design, which means that when the canvas size is scaled to 24x24, the actual icon size will be scaled to 24px as well and thus be "big".

So I was only keeping track of this "moving target" :-)

Again, no new meaning for this issue.

**Comment by dirtydancing** [comment]
@fselem For your information: I have filed a bug report against elementary GTK theme regarding the colour inconsistency over at Launchpad: https://bugs.launchpad.net/egtk/+bug/1425133

![battery_status_icon_full-charged](https://cloud.githubusercontent.com/assets/7164227/6352393/a7ca9126-bc42-11e4-9b5f-6b8858148a80.png)

**Comment by Foggalong** [comment]
Anytime I open this issue I have to let it wait for 10 seconds while all the images load :P

**Comment by dirtydancing** [comment]
@Foggalong 10 seconds only? That's pretty fast :-)

@fselem The issue with the inconsistent battery status icon colour is a "Won't Fix" from elementary OS's side. Daniel Foré writes: "I don't support using any other icon theme with this stylesheet but elementary icons. There's no way to really fix this in my stylesheet."

So, for colour consistency in the Freya wingpanel, it looks like Numix GTK theme will be the way to go.

**Comment by dirtydancing** [comment]
This is just to keep track of another moving part of the battery status icon puzze: Ubuntu's `indicator-power` package.

No action is needed concerning the issue that this thread deals with ("big" battery status icon).

Regarding the icon name that is first in line, the lastest (development) version of `indicator-power` (20150212) is staying the same as the version in Ubuntu 14.10: "symbolic"-named icons for full-charged (as well as for empty and for missing), percentage icons (not "symbolic"-named) for charging and for discharging.

What has changed though is that there now is an addition for the percentage icons for charging and for discharching: In the course of addresssing https://bugs.launchpad.net/ubuntu-ux/+bug/1388235 (targeted at mobile phones), an even finer granulation has been added for a more accurate display of the battery level, now also containing 10%, 30%, 50%, 70% and 90%.

At the same time, backwards compatibility with desktop icon themes (fallback) has been explicitly maintained. So this is only an addition, not a requirement. Everything should keep working just fine with the present Numix battery status icons.

Screenshot of the addition in indicator-power:

![indicator-power_20150212_addition](https://cloud.githubusercontent.com/assets/7164227/6425700/903179ce-bf37-11e4-93e8-9e042a3385ea.png)

In Ubuntu's latest (development) `ubuntu-themes` package (20150212), these additional percentage icons have been added to suru-icons, but not to ubuntu-mono-dark (current Ubuntu desktop default icon theme).

Screenshot of suru-icons:

![suru-icons_20150212_battery](https://cloud.githubusercontent.com/assets/7164227/6425705/ae7193c4-bf37-11e4-97f2-dd498c43d7b3.png)

Screenshot of ubuntu-mono-dark:

![ubuntu-mono-dark_20150212_battery](https://cloud.githubusercontent.com/assets/7164227/6425707/b3435072-bf37-11e4-992c-602371a46751.png)

Current overview of the battery status icons in Numix base (no changes, cf. also above):

![battery-status-icons_20141129](https://cloud.githubusercontent.com/assets/7164227/6425708/c272c62c-bf37-11e4-9f68-87035bc38c2c.png)

Draft overview of the battery status icons in Numix base (incorporating the additional percentage levels):

![battery-status-icons_20150228_draft](https://cloud.githubusercontent.com/assets/7164227/6425709/ca8cdf3c-bf37-11e4-8d9b-a2d16276d471.png)

Adding these new percentage level icons would be a new issue, as this does not concern the issue of a "big" battery status icon. As Ubuntu 15.04 is currently in development, it makes sense to first see what the final version will actually comprise. And second, the question will be whether adding these additional percentage level icons makes sense for Numix base.

Again, no action needed in the present issue ("big" battery status icon), this is just for keeping track.

**Comment by dirtydancing** [comment]
Updated icon overview after https://github.com/numixproject/numix-icon-theme/issues/331:

![battery-status-icons_20150327](https://cloud.githubusercontent.com/assets/7164227/6878195/e4af2660-d4d9-11e4-9b9e-ce3a32382178.png)

**Comment by Foggalong** [comment]
...so, Freya has been out a few weeks now. Does this issue still occur?

**Comment by dirtydancing** [comment]
As far as I am aware, the "big battery" issue does not occur on Freya. I am not a Freya user, though.

**Comment by dirtydancing** [comment]
Updated icon overview after https://github.com/numixproject/numix-icon-theme/issues/206, https://github.com/numixproject/numix-icon-theme/issues/236, https://github.com/numixproject/numix-icon-theme/issues/255, https://github.com/numixproject/numix-icon-theme/pull/283 and https://github.com/numixproject/numix-icon-theme/pull/452:

![battery-status-icons_20150502](https://cloud.githubusercontent.com/assets/7164227/7442747/46080d0e-f11e-11e4-81a7-13ac8bcd71be.png)

**Comment by Foggalong** [comment]
I spoke with Daniel in [this Reddit thread](https://www.reddit.com/r/elementaryos/comments/3c6v6v/when_doesdid_luna_support_end/cstakca?context=3) about when Luna support for this kind off issue is dropped. We agree that this issue can now be safely closed \O/
