### ISSUE TITLE
Mimetypes for Kicad

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#1111]
These are the mimetypes for Kicad projects. Any changes will be much better. The equivalent [circle issue is here](https://github.com/numixproject/numix-icon-theme-circle/issues/3265).

Here are the icons and their mimetypes:

![images](https://cloud.githubusercontent.com/assets/1277920/17199913/333ef884-5457-11e6-807f-fc20f21f6509.png)

By the way, the default **kicad** numix icon is pretty different than the original. I think it should have some elements that match with the original. 
- [ ] application/x-kicad-project :star: 
- [ ] application/x-eeschema-schematic :star: 
- [ ] application/x-pcbnew-pcb :star: 
- [ ] application/x-pcbcalculator-project
- [ ] application/x-bitmap2component-project
- [ ] application/x-gerbview-project
- [ ] application/x-cvpcb-project

**Comment by palob** [comment]
Hmm, so far the onlydraft halfway resembling anything electronics-like is this:


![electronics1](https://cloud.githubusercontent.com/assets/7050624/17314296/92e2713e-5863-11e6-887f-804f19406553.png)

**Comment by Foggalong** [comment]
Yeah, these mimetypes are going to be tricky to solve.

**Comment by leoheck** [comment]
Tricky in which sense?

**Comment by palob** [comment]
In terms of getting things like visual recognisability, symbol metaphor, pixel alignment and symbol size right.

**Comment by leoheck** [comment]
Ah, ok. I agree :)

**Comment by leoheck** [comment]
This is a simple project. Actually, the first three of the list are the most important to have. 

![selection_003](https://cloud.githubusercontent.com/assets/1277920/17416202/7894fe1c-5a63-11e6-8b60-b38b89a5690f.png)

**Comment by Jacajack** [comment]
@leoheck Alright, we're done with application icons (https://github.com/numixproject/numix-core/pull/3424). :tada:
As I told you before, I can help you with mimetype icons too. Currently I have much work to do, but I think we could start in ~2 weeks. :)

**Comment by leoheck** [comment]
Very good I already noticed the new kicad icons!!

**Comment by Jacajack** [comment]
I made a really quick draft of icon that can be used for `x-pcbnew-pcb ` mimetype. I think we should head in that direction.

![selection_001](https://cloud.githubusercontent.com/assets/6173262/20192214/3f89f474-a789-11e6-8e67-3baeadd7e1c8.png)

The track itself probably should be thinner and connect more than 2 pads (to make icon look more interesting). Or maybe there should be two of them? I''m waiting for your ideas :)

@Foggalong, could you give me some basic guidelines for this type of icons, before I start, please? I don't see any wiki connected with this repository, that's why I'm asking.

**Comment by palob** [comment]
@Jacajack I'd probably mirror that design so that you can shift it up 1px or so and the icon looks less right-heavy.

As for guidelines, the symbols should be monochrome (pure white if white) and aligned to the pixel grid.
You can use existing icons for orientation in terms of symbol size. You don't need to use the same design for each size, maybe a simpler one works better on smaller sizes.

**Comment by Jacajack** [comment]
Yeah, that looks better. I'll try to adjust pads size and track width, to make it look lighter.

![image](https://cloud.githubusercontent.com/assets/6173262/20192921/30c3f69e-a78c-11e6-895d-948b151183a1.png).

Thanks for the information. I can see that background color somewhat depends on file type (video, music, etc.). Is orange suitable here?

**Comment by palob** [comment]
Maybe that greenish-brownish-orangy colour of printed circuit boards?

**Comment by Jacajack** [comment]
Sounds good. What about schematic, and Kicad project mimetype then?

**Comment by palob** [comment]
Since all mimetypes are for one application / for electrical engineering files I'd probably use one colout for all.
Unless there is a strong colour indication in Kicad.
