### ISSUE TITLE
Xnoise status icon

### ISSUE THREAD

**Issue by ffuentesg** [numixproject/numix-icon-theme#1140]
I have problem when I use Numix Circle icons theme whith **xnoise** status icon in wingpanel
I use Elementary os 0.3.2 Freya (x64)
![xnoise numix circle](https://cloud.githubusercontent.com/assets/22458248/18852543/3302ca0e-8417-11e6-9564-6b82f17e0c5c.png)
I try copy 24 folder from _Numix base_ in _Numix-Circle_ folder but the problem not resolve
In `usr/share/applications` in the xnoise file icon line name is `Icon=xnoise`

Thanks in advance!

**Comment by wa4557** [comment]
We do have an xnoise status icon, but it cannot be used, because xnoise uses the same name for its app and status icon. You can/should report that upstream. If you want to fix that for you individually you can move `renamed-xnoise` from `22{24/16}/status` to `22{24/16}/panel` and change its name to `xnoise`
