### ISSUE TITLE
Panel icon for albert

### ISSUE THREAD

**Issue by martijnjanssen** [numixproject/numix-icon-theme#1152]
Albert is a desktop launcher. It recently started having a tray icon, more info here:
https://github.com/ManuelSchneid3r/albert

https://github.com/ManuelSchneid3r/albert/tree/master/src/application/resources

**Comment by bil-elmoussaoui** [comment]
@martijnjanssen This is impossible for us. The icon was hardcoded on the binary file, and i have reported that, but the fix we got wasn't what we were expecting... 
https://github.com/albertlauncher/albert/commit/3223a70856c08ee3177edefa5ea6034d7e7aeec2
@Foggalong a wontfix for me! As it will show the application icon instead of the indicator one anyway...
