### ISSUE TITLE
Where are the Battery Status icons located?

### ISSUE THREAD

**Issue by Hacksaurus** [numixproject/numix-icon-theme#1173]
I have dug nearly every single directory that you could possibly thing in `/usr/share/icons` and I cannot find where are the icons for the battery status: 
![screenshot_2016-12-30_11-01-02](https://cloud.githubusercontent.com/assets/24832107/21573579/fd80ce3e-ce9a-11e6-93e5-c7706b9dda90.png)

All I want to do is replace them with different pictures, or change the size of it, because it is way too big!

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/21574091/0c6063c2-ced4-11e6-9b9b-38be312a0d83.png)

``/usr/share/icons/Numix/scalable/status``

and also in the specific sizes:
/usr/share/icons/Numix/16/status
/usr/share/icons/Numix/22/status
/usr/share/icons/Numix/24/status

---

However give us more details on this bug so we can help you, it shouldn't be that big.

- What is your distro?
- Where did you install from the Numix theme? (and which version is that)
- What is your DM? (Gnome, KDE, Xfce, etc)

**Comment by Hacksaurus** [comment]
My distro is Arch, and I installed it from the AUR repository, and my DE is XFCE
And I see that those icons are there, that is good! 
The thing is that why are the icon is so big on the panel?... Is it possible for me to make it smaller?
Also I have noticed that it sometimes inaccurate, this might not be a problem with the icons, but just something I have noticed...

**Comment by hlechner** [comment]
@Hacksaurus I'm also an arch linux user however I'm using Gnome instead of Xfce.

So I can't be sure about, but I can guess:

Xfce uses GTK too, the GTK themes can define many things as the sizes of borders and some panels, so if the theme explicit change the size of panel, maybe it start to use the icon from the lower dimension or higher (depending on config), for example if doesn't have space to display a 64px maybe it can display a 48px or a 32px.

It's just a guess, but I faced this issue on gnome2 a many years ago due to a GTK theme.

But how about different icon themes, it doesn't happen when using arc GTK theme?

**Comment by Hacksaurus** [comment]
Well to test if it is the GTK theme is the problem could you tell me how to just change the GTK theme @hlechner ? That would be helpful!

**Comment by hlechner** [comment]
The GTK theme is what you have changed on screenshots.

Adwaita = is the default gnome theme for example.

It's possible to install a Numix GTK theme to test if you like it:
```
community/numix-themes 2.6.5-1
    A flat and light theme with a modern look (GNOME, Openbox, Unity, Xfce)
```
You can install it with pacman/yaourt.

Or the numix-theme from a antergos version (which is blue) from AUR:
https://aur.archlinux.org/packages/numix-frost-themes/

---

And if you want to use the Arc theme, could be a good idea to raise an issue to the theme developers:
https://github.com/horst3180/arc-theme

**Comment by Hacksaurus** [comment]
Installing the Numix theme didn't help, but I'll sure try to ask the people who made Arc!
I'll close this thread for now, because it seems icons is not the problem... 
Thanks for the help though!

**Comment by hlechner** [comment]
You're welcome!

If need my help on the issue on arc-theme side just mention me there.

**Comment by hlechner** [comment]
Just the last test if it is possible:

Could you try to use a different icon theme? to check if the sizes of the battery and speakers will remain the same as the Numix. Because I've see that only the battery change the size but the speaker remain the same (as your screenshot)

**Comment by Hacksaurus** [comment]
Changing the icon theme does change the battery icon (With a different icon), but the speaker does not change. I think that might be because its the `xfce4-pulseaudio-plugin`, and that has its own seperate icon...

**Comment by Hacksaurus** [comment]
Actually I think it might be a good idea to try to install this forked version of the Arc Theme, and this forked version of the Numix Icons... I saw that they had fixed both of those problems, when I was using Ubuntu!

https://github.com/GalliumOS/Arc-theme
https://github.com/GalliumOS/numix-icons-galliumos

**Comment by hlechner** [comment]
If you do want to try to change something in the GTK theme files you can found it in the following path:
```
/usr/share/themes/
```

Or as an alternative you can use a "bad" workaround: remove the battery icons from the scalable folder:
``/usr/share/icons/Numix/scalable/status`` then you be available only the sizes 16,22 or 24 if you want it be displayed as 24px it will be enough, if you want it be displayed as 16px for example you can remove the 22px and the 24px as well.

But it is a bad workaround because any application that uses the icon will be forced to use the only sizes remaining.

---

This issue doesn't need to stay closed for now, however I'm not a member of numix so I can't re-open it.


Maybe it can be caused by some panel configuration on your xfce? like the pulseaudio-plugin that you mentioned. Because the configuration that I have tested the xfce some months ago the panel was a lot smaller.

**Comment by Hacksaurus** [comment]
Removing those did not work... But I think I found another problem... The power manager plugin is not accurate and I think I know why... I have battery icons that go 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, and I think it is not using that, and instead using Full, Good, OK, Low, and then Caution, which just link to some of the battery things... But anyways I think I'm just going to give up...
I kind of want to use i3 now! 
Thanks again!
