### ISSUE TITLE
Folder icon shown in panel

### ISSUE THREAD

**Issue by ramzydoni** [numixproject/numix-icon-theme#1231]
i have request for numix icon
I noticed in all icons"paper-papers-moka..." there is an" icon desktop "in the Office ribbon panel
But in Numix there is nothing ... is a file 0_o?

http://i.imgur.com/XxNRR5O.png

I think you should update this icon
  Thank you

**Comment by palob** [comment]
That's the "show desktop" icn, right?

What's your desktop environment?

**Comment by ramzydoni** [comment]
hey i user xubuntu The desktop environment is xfce.

**Comment by bil-elmoussaoui** [comment]
We can't do anything about it, as this icon is meant for places context and used in almost every folder manager as a "Desktop" Folder icon. Changing this icon will just cause some inconsistent icons there. The best way to fix this is to report upstream to XFCE devs and ask them to use an action icon instead of places one.

**Comment by Foggalong** [comment]
Yeah, it was a Numix design choice to make all the folders show in file managers folders, rather than specific symbols as some other icon themes do.
