### ISSUE TITLE
Icon in system tray for Protonmail Desktop

### ISSUE THREAD

**Issue by Faust30000** [numixproject/numix-icon-theme#1267]
Please add an application icon for the program ProtonMail. This is the only application for this mail, but it lacks the Numix icon in the tray.

**Comment by bil-elmoussaoui** [comment]
I have never heard about this. I just took a look at their website and they don't seem to have an official client. Can you please give us more information? like the app link (i guess it's an electron wrapper?)

**Comment by Faust30000** [comment]
Yes, this is an unofficial application on an electron.
https://github.com/protonmail-desktop/application

**Comment by bil-elmoussaoui** [comment]
The icons are hardcoded. We should add the ProtonMail support to hardcode-tray first and then add the icons on Numix 👍

**Comment by Faust30000** [comment]
Please, added icon ProtonMail to hardcode-tray.
By the way, the Telegram, TeamViewer, RedShift icon also does not appear in the tray, although it is in the Numix Icon.

**Comment by bil-elmoussaoui** [comment]
You should use hardcode-tray to fix Telegram, redshift is not hardcoded. TeamViewer icons are hardcoded, it was working with Hardcode-Tray but it doesn't work anymore

**Comment by Faust30000** [comment]
Hardcode tray working on Cinnamon?

**Comment by bil-elmoussaoui** [comment]
Please open an issue on Hardcode-Tray repository or join our Gitter channel in order to keep this issue clean.
I have added ProtonMail support to Hardcode-Tray. 
The icons are 
- `protonmail-indicator`
![icontray](https://user-images.githubusercontent.com/7660997/32889695-3619fada-cacc-11e7-9819-a0ed24489b5a.png)
- `protonmail-notification`
![icontrayunread](https://user-images.githubusercontent.com/7660997/32889699-3a70fa16-cacc-11e7-98b8-e1a1dcfc374c.png)
