### ISSUE TITLE
Change this icon (I can't find the name)

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-icon-theme#1319]
> This picture is a screenshot of pamac 7.x in Numix Circle icon theme
> 
> ![pamac in numix circle](https://user-images.githubusercontent.com/11488886/49055086-eaff1780-f228-11e8-9f05-bb62a8bd7dba.png)
> 
> This picure is screenshot of the same app in Adwaita icon theme
> 
> ![pamac in adwaita](https://user-images.githubusercontent.com/11488886/49082381-3393f080-f27c-11e8-9c0c-e5a595c52179.png)
> 
> The Adwaita version has the icons (checkboxes) distinguishable whilst the Numix version has not.

Moved from https://github.com/numixproject/numix-core/issues/4637

**Comment by Foggalong** [comment]
I've come across this issue before and in short it can't be fixed for pamac without breaking other GUI package managers. It's an upstream issue with Pamac choosing to use icons for checkboxes rather than GTK elements. Rather than it being that Adwaita is actually covering the needed icons, it's that Adwaita doesn't have the icons and so its resorting to pamac's own fallback icons.

**Comment by KSXGitHub** [comment]
Seems like pamac made a poor decision.

**Comment by Foggalong** [comment]
Indeed :sweat_smile:
