### ISSUE TITLE
Gnome Shell 3.34 Battery Icon

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#1339]
See this [issue](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1908) for the Papirus icon theme. In short, it looks like they've addressed #966, #1314, and [this issue](https://gitlab.freedesktop.org/upower/upower/issues/49) in upower by adding more granularity to the power manager icons. We'll address this as Papirus have, keeping the same designs but just adjusting our levels.

**Comment by Foggalong** [comment]
Out of curiosity, are there any distros shipping 3.34 OTB yet? I live on LTS releases these days so my version of GNOME is a little way behind.

**Comment by palob** [comment]
Arch, Manjaro, Fedora. Ubuntu 19.10 will have it.

**Comment by Foggalong** [comment]
Ahh damn, I suppose it is nearly October already we've missed the 19.10 general package freeze (August 22nd if I'm reading the schedule right) but we can still aim to have it in the PPA at the very least by release day.

**Comment by dirtydancing** [comment]
Just quickly checking in to say that with regard to the battery status icons chart at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-98399311, this should be a pretty straightforward case of adding 22 "level"-named "symbolic"-named battery status icons to the scalable status directory; for the exact icon names cf. https://gitlab.gnome.org/GNOME/adwaita-icon-theme/tree/master/Adwaita/scalable/status. Not least because of the unique icon names including "level", no breakage is to be expected elsewhere.

**Comment by Foggalong** [comment]
You bae I fully wasn't expecting a response on this! That's reassuring :smile:
