### ISSUE TITLE
Potentially Broken Icon?

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [numixproject/numix-icon-theme#1358]
The icon in the far left of this looks really odd, kind of stretched, is it broken? And if not, any chance we can improve it?

![80939460-9a53fc80-8dd4-11ea-9801-0f7a644af483](https://user-images.githubusercontent.com/7698035/81041298-6c8ab880-8ea5-11ea-8d2a-88b12b07b148.png)

**Comment by palob** [comment]
Original discussion here https://github.com/numixproject/numix-icon-theme-circle/issues/124

**Comment by Foggalong** [comment]
It's not broken, it's the icon for fog which is hard to symbolise with just solid shapes. The most common iconography is a series of horizontal lines or blobs to represent the fog itself and then sometimes another object being obscured in the background (though that's a little too much detail for a status icon.

I'm going to tentatively mark this as wontfix because I've not seen anything else to represent it which would be both recognisable and better design wise than this, but if anyone does have any ideas happy to accept PRs on this issue.

**Comment by KUPOinyourWINDOW** [comment]
Yeah, that's fair enough. Given the context and a little googling I see exactly what you're saying.
