### ISSUE TITLE
Mimetype icons not working in owner user.

### ISSUE THREAD

**Issue by MauricioGlz** [numixproject/numix-icon-theme#142]
The mimetype icons do not work in thu own user, but they work if you acces remotely to another PC/Server with other user.

To reproduce the bug, I connected to a ftp server (with user and password), in there all the files have their respective icons (.css, .html, .js, .php, etc) but if copy the files to the local PC, the icon stop working and shows the generic file icon. 

These are the screenshots of the bug.
![captura de pantalla de 2014-06-24 09 48 01](https://cloud.githubusercontent.com/assets/868743/3413117/e0de8e3a-fe07-11e3-9730-e6da22d728cf.png)
![captura de pantalla de 2014-06-24 09 48 52](https://cloud.githubusercontent.com/assets/868743/3413118/e0e1a52a-fe07-11e3-8731-74e5e962e130.png)

**Comment by abderrahmane-tj** [comment]
I have the same problem, I am using Ubuntu 14.04.1 LTS, Kernel 3.13.0-45-generic.

I should also add, that the icons show correctly in unity search, but not in nautilus 

![screenshot from 2015-02-17 11 38 55](https://cloud.githubusercontent.com/assets/302837/6227632/33e4d09e-b69a-11e4-949d-71786655020c.png)

![screenshot from 2015-02-17 11 39 55](https://cloud.githubusercontent.com/assets/302837/6227633/33e997fa-b69a-11e4-9d8a-a3fe0a819541.png)

**Comment by abderrahmane-tj** [comment]
@MauricioGlz @BallroomProgrammer @Foggalong @bil-elmoussaoui  @dgladkov I found out where this is coming from. It is not caused by Numix. It is caused by Nautilus itself.

This happens when you have Show Preview Thumbnails activated in Nautilus. When I change it to never, the icons show properly. 

Here is how to fix it : Edit > Preferences > [Preview Tab] > Show Thumbnails : <Never>

The only issue now, is that you don't have preview for images and other mime-types you want preview for. I'll update on that if I find a solution for previews

**Comment by abderrahmane-tj** [comment]
Alternatively you can use this method to disable thumbnails for specific mime types http://askubuntu.com/questions/518889/how-to-disable-thumbnail-generation

(although it does not work for me yet)

**Comment by Foggalong** [comment]
@abderrahmane-tj Thanks for the information! Hope it's of use to the rest of you having this problem :)
