### ISSUE TITLE
New Wifi Status icon

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#330]
The wifi status icon could do with a revamp

**Comment by wa4557** [comment]
What you think about this one? The spacing doesn't really fit with the rest of the status icons imo.
Another matter altogether might be the `network-offline` icon, since I see no reason why a wifi icon is used right now...
![bildschirmfoto vom 2015-08-30 22 52 41](https://cloud.githubusercontent.com/assets/6475757/9569391/0c25f7e0-4f6a-11e5-98b5-66aa87a2ad29.png)

**Comment by wa4557** [comment]
@Foggalong Any feedback on this one? (Maybe you missed it during your convalescence :)

**Comment by Foggalong** [comment]
I did! I do like this new style, and it fits in with the style of the batter icons too :D

**Comment by wa4557** [comment]
Glad to hear that! Looks way better in the tray, I'll add them asap, but it requires more work, because I also have to redesign the animations. Any idea about this one? I think for this one a redesign is even more urgent (`nm-no-connection`) ...
![bildschirmfoto vom 2015-09-13 20 34 47](https://cloud.githubusercontent.com/assets/6475757/9838184/ea528b5e-5a56-11e5-8510-9b53803d0563.png)

**Comment by Foggalong** [comment]
Yeah, having the no-connection in the specific design on the wireless icon (excluding wired, 3G, etc) is a bit problematic but I'm not sure what the other solution would be. As far as I'm aware there isn't a universally recognised symbol for no connection :(

**Comment by wa4557** [comment]
So you recommend to keep it he way it is (adapting the size/shape of course)?

**Comment by Foggalong** [comment]
Yeah, as is for now. If any ideas are had though down the line I'd be more than happy to use them instead :)

**Comment by bil-elmoussaoui** [comment]
In gnome i still have the old design, is this normal?
@dirtydancing can you check this out too as you're using Gnome too

**Comment by Foggalong** [comment]
It would seem that the `/scalable` icons were [left out](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/scalable/status/network-wireless-signal-ok-symbolic.svg) in this update.

**Comment by wa4557** [comment]
Indeed didn't think about them, I'll add them asap :)

**Comment by Foggalong** [comment]
:+1:

**Comment by dirtydancing** [comment]
Confirmed that the wifi icons in GNOME Shell have not changed so far. Personally, I think the current wifi icons fit quite nicely with the sound/volume icons, which in GNOME Shell panel show next to each other.

**Comment by wa4557** [comment]
The new one fits even better :P

**Comment by dirtydancing** [comment]
OK :) Just to show what I mean, here is a current screenshot with Arch/GNOME (3.18):

![wifi](https://cloud.githubusercontent.com/assets/7164227/10563858/401d98c0-759c-11e5-8781-ccb5f020010b.png)

**Comment by dirtydancing** [comment]
Confirmed that the new wifi icon design is showing with GNOME Shell now. Looking good :+1: 

![wifi_new](https://github-cloud.s3.amazonaws.com/assets/7164227/10565519/6e5283fa-75d2-11e5-8fac-b140e1126307.png)
