### ISSUE TITLE
Frequently Searched Folder

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#428]
I keep meaning to look and forgetting to putting this here as a reminder; is this folder in Firefox themeable by icon themes?

![screenshot - 040415 - 12 33 57](https://cloud.githubusercontent.com/assets/5920259/6992447/e531ec38-dac6-11e4-8407-6ae81e8b6c24.png)

**Comment by bil-elmoussaoui** [comment]
the icon is : folder-saved-search but i don't think it's themable (i didn't try), elementary comes with a redesigned icon but its not working.

**Comment by Foggalong** [comment]
Thanks for finding the name. Chief tester @dirtydancing, fancy giving it a bash?

**Comment by dirtydancing** [comment]
Haha, sure thing! :-) I can't do it right now, will get back to you.

**Comment by dirtydancing** [comment]
Hmm, from what I am aware of so far, I believe this icon is not themeable, at least not in the standard way. I have come across this icon in Thunderbird:

![saved-search](https://cloud.githubusercontent.com/assets/7164227/7065669/6ef0f454-deba-11e4-8b51-793f9850896a.png)

This might be themeable via special themes for these specific apps. In the past, there has e.g. been a monochrome Thunderbird icon "patch" for Ubuntu, but that has not been shipping with Ubuntu anymore because there were several icons missing, cf. https://bugs.launchpad.net/ubuntu/+source/thunderbird/+bug/1347124.

**Comment by dirtydancing** [comment]
Some more evidence suggesting that while some folder icons are themed/themeable, this does not seem to apply to this icon. This is from the bookmarks menu of current Firefox 37.0.2:

![folder-icons](https://cloud.githubusercontent.com/assets/7164227/7336577/8e11bc1c-ec05-11e4-9f72-cb21aab23caa.png)

**Comment by Foggalong** [comment]
We have the icon too. Switching to hardcoded and closing :'(
