### ISSUE TITLE
Touchpad indicator fixes

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#444]
Hello, 
In the last commit that fixes Touchpad-indicator the icons in the Numix-light are:
- touchpad-indicator-light
- touchpad-indicator-light-disabled
- touchpad-indicator-light-enabled

The icons name must be changed from light to dark.
Thanks!

**Comment by wa4557** [comment]
I'm not so sure about that. What sense does it make to have a dark tray icon if all your other icons are light (or the other way around)? This approach of creating *light.svg and *dark.svg icons is per se a bad idea, and it makes no sense imo to make the same thing in Numix. What is possible and could be done is a symlink from touchpad*-light.svg to touchpad*-dark.svg; but in Numix AND Numix-Light

**Comment by bil-elmoussaoui** [comment]
Well, the icons for the touchpad-indicators are in /opt/extras.ubuntu.com/touchpad-indicator/share/touchpad-indicator/icons
![capture du 2015-04-09 18 22 33](https://cloud.githubusercontent.com/assets/7660997/7071412/675d57a2-dee5-11e4-84da-423a066ace6b.png)
And they uses the touchpad*-dark.svg for the non light indicators.

**Comment by wa4557** [comment]
In the app. Is there somewhere a setting that let you choose between dark and light icons?

**Comment by bil-elmoussaoui** [comment]
Yes! 
![capture du 2015-04-09 18 28 55](https://cloud.githubusercontent.com/assets/7660997/7071554/53847b74-dee6-11e4-9738-7b36e55e6085.png)

**Comment by wa4557** [comment]
In this case my approach is the right one imo. Symlink touchpad-\*-light.svg to touchpad-\*dark.svg in Numix and Numix-Light. Let's see what others have to say

**Comment by dirtydancing** [comment]
Actually, in my view, this kind of issue should be solved in a kind of "third" way: by having **both** panel icons in Numix and **both** corresponding symlinks in Numix-Light.

Indeed, an app that provides light and dark panel/status/indicator icons actually creates a complication. Another example of this I have come across is Variety, cf. e.g. https://github.com/numixproject/numix-icon-theme-circle/issues/1245. Variety lets you choose between a light and a dark panel icon (and provides other choices as well, such as the current wallpaper).

Screenshot of the Variety settings page, current PPA version 0.5.3:

![variety-einstellungen](https://cloud.githubusercontent.com/assets/7164227/7084444/bf1a4a1c-df6d-11e4-8294-2bbed43377a5.png)

In Variety, the icon names are `variety-indicator.svg` and `variety-indicator-dark.svg`.

Alas, from this point of view this is actually currently not correctly implemented in Numix/Numix-Light, because in Numix-Light, the icon `variety-indicator.svg` is used for the dark panel icon. This leads to the result that when a "light" panel icon is selected (default setting), the Numix dark panel icon shows when Numix-Light icon theme is selected. But when the "dark" panel icon is selected, the original non-Numix dark Variety panel icon is displayed. That sets the user up for confusion.

The special naming of dark panel icons as `*-dark.svg` is also confusing in another way: a "light" icon theme may be named "light" because the panel is light or because the icons are light. E.g., Numix-Light is for **light** panels with dark icons (same for ubuntu-mono-light), but Faba-Mono-Dark from Moka Project is for light panels with **dark** icons. This also can cause additional confusion for the user.

For Numix/Numix-Light, to me this means indeed that **both** panel icon variants have to be present in Numix and in Numix-Light. This means both icon files in Numix, and symlinks to both in Numix-Light. If the user uses a light icon theme and gets a light icon in the panel, the user can choose a dark panel icon via the specific app, just like the app developer intended.

If not **both** panel icons/symlinks are present in Numix and in Numix-Light, the user will be presented a non-Numix icon depending on the choice of panel icons.

And having e.g. in Numix-Light only a dark panel icon (via symlinks) would preclude the user from the choice that the app developer intended. And I figure that it would be confusing to be presented a dark icon with Numix-Light, no matter if a light or a dark panel icon is selected in the apps settings.

@bil-elmoussaoui @wa4557 What do you think? Convined? :-) Any other ideas?

**Comment by wa4557** [comment]
@dirtydancing Not entirely :) but I could live with that... I still think that it's kind of useless to have light icons in a dark theme, kind of defeats the purpose...

**Comment by dirtydancing** [comment]
@wa4557 Agreed that it is basically useless. But if an app provides a choice between a light and a dark panel icon, to me it seems that it is even more confusing to "override" that choice by only providing one (light or dark) panel icon for both.

And actually, by a wild stretch of imagination, there might even be a use case for e.g. a light panel icon in a dark theme: Imagine a transparent panel with a light-coloured wallpaper that has a dark stripe in it, and the panel icon for e.g. Variety is located exactly on this dark stripe. You would then be happy to be able to choose a light panel icon just for Variety, while all the other panel icons are dark :-).

Haha, just imagining here, I agree with you that the approach of creating "light" and "dark" panel icons with different icon names is a bad idea of the **app**. So the **app** itself is where this should be fixed.

**Comment by dirtydancing** [comment]
I created a pull request with the corresponding changes for touchpad and for variety (both light and dark in Numix as well as in Numix-Light), cf. https://github.com/numixproject/numix-icon-theme/pull/457.

As long as this is the approach for apps that include a choice inbetween light and dark status/indicator icons, please let me know if there are more apps with this kind of choice and correspondingly with different names for light and dark icons. For consistency, these would have to be adapted to this approach as well.

**Comment by bil-elmoussaoui** [comment]
There's one more app that i use : gdrive but the indicator icons arr hardcoded but you can create a symlink for that too

**Comment by dirtydancing** [comment]
@bil-elmoussaoui OK, let's see how this issue will get sorted and merged, and to keep this as simple as possible, I would suggest to then have any additional indicator icons in separate new issues :)

**Comment by bil-elmoussaoui** [comment]
I will open a new one asap ;) Thanks
