### ISSUE TITLE
Remove network-wired from 16 22 and 24/status

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#458]
I suggest to remove `network-wired` from the `status` folders for sizes `16` `22` and `24` and replace it by symlinking it to nm-device-wired in `devices`.
Reasons:

1. Unnecessary: I tested this using Ubuntu and Cinammon, and it seems to me that they are not needed for displaying the wired network status. This icon is not used at all, and changing it does not change anything in the status bar. @dirtydancing Fancy testing that as well?

2. This icon is used in the Ubuntu-network setting and when using Numix as icon theme it is hardly recognizable (screenshot). If one creates a symlink to ǹm-device-wired.svg` in `devices` it looks way better.
![bildschirmfoto vom 2015-04-14 12 18 06](https://cloud.githubusercontent.com/assets/6475757/7135459/33e2a9ac-e2a7-11e4-980c-9a4f86fa21e0.png)
![bildschirmfoto vom 2015-04-14 12 19 56](https://cloud.githubusercontent.com/assets/6475757/7135460/350a0910-e2a7-11e4-9fee-f42469fa63f6.png)

3. Consistency: `network-wireless.svg` is only present in `devices` and is no monochrome icon. Why treat it differently than the wired icon?

4. According to #189 `network-wired-disconnected` is still missing. This one could also be placed in `devices` and would be consistent with this new approach

**Comment by dirtydancing** [comment]
Sure thing! I will have a look at this. As to 1. "unnecessary": iirc, in the panel `nm-device-wired.svg` is used, so no need for `network-wired.svg` for the panel indeed.

**Comment by wa4557** [comment]
As a side note: `network-wireless-encrypted` also should be moved from `status` to `devices` since it falls into the same category...

**Comment by wa4557** [comment]
Since we are already talking about this icons: Here's a suggestion for an updated nm-device-wired (soon to be network-wired :) icon). The old one was from the elementary-theme and didn't quite fit the Numix style. 
![test](https://cloud.githubusercontent.com/assets/6475757/7143356/47861af6-e2df-11e4-936d-2f457a3f13a7.png)
![test2](https://cloud.githubusercontent.com/assets/6475757/7143355/4784471c-e2df-11e4-8e09-fd351f1e9bd3.png)

Better or worse?

**Comment by dirtydancing** [comment]
I agree with the approach as suggested by @wa4557.

Checked against daily Ubuntu 15.04:

1) Confirmed that the panel uses `nm-device-wired.svg` from `status`. If this icon is not present in `status`, the panel will display `nm-device-wired.svg` from `devices`, so this icon has to be in `status` as a monochrome status icon (and it presently is). This only confirms what has already been discussed e.g. in https://github.com/numixproject/numix-icon-theme/issues/209.

2) Confirmed that `network-wired.svg` is used in the network system settings and is hardly visible if taken from Numix. An alternative way around this would be to symlink in Numix to the monochrome dark icon in Numix-Light, but that would be indeed inconsistent with `network-wireless.svg` in devices. So I agree with the approach of symlinking `network-wired.svg` in `status` to the target `nm-device-wired.svg` in `devices`.

3) NEW and related: For some reason, in Numix base in `22x22/devices` there is an inconsistent icon for `nm-device-wired.svg`, still with the old status icon design. That should be replaced with the otherwise consistent non-monochrome icon as displayed above, and it would make sense to include that change in this context.

Screenshot from `22x22/devices` (not `status`):

![devices_nm-device-wired](https://cloud.githubusercontent.com/assets/7164227/7142937/77a1896c-e2dc-11e4-8db6-9eaf25bf1b1a.png)

4) As a side note: to me, the non-monochrome ("golden") `nm-device-wired.svg` in `devices` looks somewhat out of line with the other Numix icons, also e.g. when compared to `network-wireless.svg`. This might be a good opportunity to redesign that icon (?). Not really sure how, though :)

Screenshot of current `48x48/devices`:

![48x48_devices](https://cloud.githubusercontent.com/assets/7164227/7143317/08df9e58-e2df-11e4-85d5-a5223c652fdc.png)

**Comment by dirtydancing** [comment]
@wa4557 Haha, cross-posted :-) So we agree that the current `nm-device-wired.svg` in `devices` looks somewhat odd in Numix :-)

**Comment by wa4557** [comment]
Oh yes, this is arguably the ugliest icon in the whole theme

**Comment by dirtydancing** [comment]
So why not take a modified version of the icon that is presently in `22x22/devices`, cf. screenshot above (and btw this icon design is also in `48x48/notification`, so that would be a consistent design)?

**Comment by wa4557** [comment]
So something like this? Idk looks a little bit dull to me...
@Foggalong What do you think, keep the old one or change it?
![test](https://cloud.githubusercontent.com/assets/6475757/7143766/6c71447e-e2e1-11e4-9116-fccdb66798d3.png)

**Comment by dirtydancing** [comment]
Well, yeah, but this would not need to be monochrome. Agreed, just like that, too dull :)

**Comment by dirtydancing** [comment]
I figure this could also be a version of the counterpart, the actual plug socket. Basically, from my perspective, probably anything that is completely different from the current icon :) (and ideally consistent with corresponding "wired" icons already present in Numix base).

**Comment by dirtydancing** [comment]
Opened two separate issues for the separate aspects that have come up above, cf. https://github.com/numixproject/numix-icon-theme/issues/460 and https://github.com/numixproject/numix-icon-theme/issues/461.

**Comment by wa4557** [comment]
Fixed. Closing
