### ISSUE TITLE
Panel bar sound icon smaller than the others

### ISSUE THREAD

**Issue by pedrofleck** [numixproject/numix-icon-theme#459]
I'm using Arch with the git package from AUR and Gnome 3.16. The volume icon in the panel bar is smaller than the power and network icons making it low res and ugly (screenshot attached), how can I fix it?
![captura de tela de 2015-04-14 21-43-58](https://cloud.githubusercontent.com/assets/761321/7150299/635bb29e-e2ef-11e4-86cf-09f74220b8cf.png)

**Comment by dirtydancing** [comment]
Hi, are you sure that this is not the Numix icon? What should it look like in your view? I am asking because this looks like the Numix icon to me.

The volume icon in your screenshot should be `audio-volume-medium-symbolic.svg` from the`scalable/status` directory. Screenshot of that icon in Numix:

![numix](https://cloud.githubusercontent.com/assets/7164227/7155060/ee410e56-e35b-11e4-9041-1db1bd872169.png)

In contrast, at least in the version of gnome icon theme shipping with Ubuntu 14.10, that icon in gnome looks like this:

![gnome](https://cloud.githubusercontent.com/assets/7164227/7155063/0296b0ea-e35c-11e4-916e-c1dd8cc7d8e3.png)

**Comment by freckts** [comment]
Yeah, you're right, but why the icon is smaller? It happens with every GS theme and was present in 3.14 too.

**Comment by dirtydancing** [comment]
Was it different before GNOME 3.14? The volume icon in your screenshot might just look smaller because the `network-wired-symbolic.svg` icon next to it looks somewhat "massive" in comparison. This is a screenshot with both icons next to each other, and this looks just like in your screenshot. One possible way to address this would be e.g. to redesign the `network-wired-symbolic.svg` icon:

![icon-sizes](https://cloud.githubusercontent.com/assets/7164227/7160820/be532280-e38b-11e4-8796-4edc18ec23ad.png)

**Comment by dirtydancing** [comment]
To illustrate, here are some screenshots of Ubuntu GNOME 15.04 beta 2 with default GNOME Shell 3.14.4. As you can see, with Numix icon theme the volume icon looks quite small in comparison indeed:

GNOME icon theme:
![gnome](https://cloud.githubusercontent.com/assets/7164227/7161959/47ecf6e6-e392-11e4-955b-a5d3260ae199.png)

Adwaita icon theme:
![adwaita](https://cloud.githubusercontent.com/assets/7164227/7161960/4bbd3cfe-e392-11e4-8a9a-8ee09d5deafb.png)

Numix icon theme:
![numix](https://cloud.githubusercontent.com/assets/7164227/7161968/5161a7da-e392-11e4-8679-2dc917d47bc7.png)

**Comment by dirtydancing** [comment]
So apparently, this is the regular current design in Numix and not a bug :). In conclusion, to me, this issue suggests an enhancement of the sound/volume icon in the `scalable/status` directory to make it somewhat "bigger", so that it matches the other panel icons for GNOME Shell, e.g. wired and battery.

**Comment by dirtydancing** [comment]
To clarify: I agree with this issue report, and that there is a size inconsistency with the sound icon. But this only relates to GNOME Shell and thus only to the sound icon(s) in `scalable/status`.

In contrast, this problem is not present in the fixed size status directories. Screenshot of Ubuntu 14.10 with current Numix base via PPA (panel icon size: 22x22, relative size of the sound icon is just fine):

![ubuntu1410_sound](https://cloud.githubusercontent.com/assets/7164227/7166086/fc598f9a-e3ab-11e4-9b55-3f17f4e93999.png)

**Comment by pedrofleck** [comment]
So, the volume icon is smaller and the power and wired network are bigger than the Adwaita one and it's only seen in Gnome Shell; assuming that's a icon theme, how this cannot be a bug? 
Anyway, there's something I can do about it? A way to use Adwaita's network icons or something like that?
Thanks!

**Comment by dirtydancing** [comment]
@pedrofleck Please do not worry about the labels "bug" or "enhancement" :)

Basically, GNOME Shell uses different icon names for the panel than e.g. Unity, so GNOME Shell has a corresponding, but different set of icons for the panel. The sound/volume icon with Numix icon theme is displayed just like it is currently designed in Numix icon theme (so this is not a "bug").

Please also take into consideration that other users may not be perceiving this as irritating. At least this appears to be the first time that this has been reported.

What can you do about it? Well, you already reported the issue, thanks!

If you feel like mixing icon theme, you might indeed replace the Numix network (or sound) icons with Adwaita icons: for that, you would need to overwrite the icon(s) in Numix with the ones in Adwaita. The icon names have already been mentioned here, and the relevant directory is `scalable/status`.

Please do not hesitate to ask if you are in need of further assistance.

**Comment by wa4557** [comment]
@pedrofleck How does it look now? it should be fixed. Could you possibly provide a screenshot?

**Comment by dirtydancing** [comment]
@pedrofleck For your information: this has been addressed from the network as well as from the volume icon. Screenshots of before above and current below:

![before](https://cloud.githubusercontent.com/assets/7164227/7582940/28032cc8-f892-11e4-9bbe-ed1ef74ced78.png)

![current](https://cloud.githubusercontent.com/assets/7164227/7582934/1f4167a8-f892-11e4-8c78-bdea0fd114ab.png)

**Comment by pedrofleck** [comment]
Awesome. Thank you!
