### ISSUE TITLE
Enhance notification icons

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#473]
Issue concerning all *buntu distributions.
This issue only makes sense if most of the current pull-requests (esp. #468) are merged and #472 is addressed:
The current notification icons are basically scaled up status icons. I think it would be better if icons from `devices` would be used, because that would mean that they are less grey and dull. An excpetion for that would be the sound notification and brightness notifications because they are somehow special considering their placement and greyish progress bar.

So my idea would be something like this:

![bildschirmfoto vom 2015-04-29 14 17 39](https://cloud.githubusercontent.com/assets/6475757/7390671/baf4c0f4-ee7a-11e4-9e1c-ee82fc59e52b.png)

- Symlink battery icons from devices to notifications (only works if and when #452 is merged). 
- Symlink `network-wireless` in `devices` to `nm-device-wwan` in `notifications`. 
- Symlink `nm-device-wired` in `devices` to `nm-device-wired` in `notifications` (the icon will probably look different in the future, see #468).
- If #472 is addressed symlink `nm-device-wireless`in `devices` to `notifications` (if #472 is not addressed do that as well, but change the design of `notification-network-wireless-disconnected`)
- If #468 is merged (that's the reason the symlink is broken currently) symlink `network-wired-disconnected` to `notification-network-ethernet-disconnected` and 
- design two new icons for `notification-network-wireless-disconnected` and `notification-gsm-disconnected` (my suggested icons can be seen in the screenshot). 

This generally leads to nicer notifications and solves the bug, that Xubuntu takes `nm-device-wired` and `nm-device-wireless` from `devices` instead of `notifications` for its notifications

**Comment by wa4557** [comment]
Some screenshots, why I think this is an improvement:

Battery notification
![bat](https://cloud.githubusercontent.com/assets/6475757/7390924/f231673c-ee7c-11e4-8613-bcd03739386a.png)

wireless-disconnected:
![nm-device-wireless](https://cloud.githubusercontent.com/assets/6475757/7390934/fdb5b392-ee7c-11e4-8dc2-cc8bffd2c925.png)

wireless-connected
![wwan](https://cloud.githubusercontent.com/assets/6475757/7390937/04963c90-ee7d-11e4-83d9-4694619c50bc.png)

wwann-connected
![disc](https://cloud.githubusercontent.com/assets/6475757/7390929/f89c57d0-ee7c-11e4-923e-a6aa46bbdd1b.png)

**Comment by dirtydancing** [comment]
Well, I am not sure about this one. To exchange some arguments (and I will be fine no matter how this turns out :), let me start with this:

1) I think these notification icons are/should be `status` icons and thus should be designed in a status icon way, like currently. The `device` icons are supposed to be shown permanently, whereas the notifications come and go (showing a status) and thus have to work in a quick fashion. The `status` design is simpler and catchier.

2) Relating to 1): the icon names that are displayed in the notification bubbles in practice for the "connected" status, e.g. `nm-device-wired.svg` do not appear to be the names that these notifications were designed for. In theory, the proper icon name would be `notification-network-ethernet-connected.svg` and so on, but these icons are not picked up. It is no coincidence that e.g. in Xubuntu 15.04, in the default icon theme `nm-device-wired` is a symlink with the target `notification-network-ethernet-connected` :) This should not be handled that way in Numix, I am only mentioning this to show that the proper notification icon name would not be a `device` icon name.

3) To me, it makes sense that the notification icons are consistent with the design of the status icons in the panel. No confusion caused by a quick glance at the notification bubble.

4) To me, it also makes sense that all the notification icons are consistently designed (just as volume and brightness), like currently in the `#ececec` colour that is also used for the panel status icons.

5) Specifically for the battery icons: currently with the orange and red colour, they have a very visible warning function. The design above (whicht is due to the `device` icon displaying different states in the Ubuntu "energy statistics") to me does not fullfill this warning adequately.

6) For a quick notification glance, I am not sure if `nm-device-wireless.svg` and `nm-device-wwan.svg` above look different enough. They are distinct icons for the `device` purpose, but not necessarily for the notification purpose. 

What do you make of this?

As a comparison, here is an overview of the current notification icons:

![notification-icons](https://cloud.githubusercontent.com/assets/7164227/7401262/ffc1da3a-eec2-11e4-9965-63e394f9d868.png)

**Comment by dirtydancing** [comment]
Let me add one more aspect to this:

7) At least in Ubuntu, the colour of the notification bubble background is based on the colour of the wallpaper. This means that the less "coloured" and detailed the notification icons are, the less potential for visual "breakage".  To me, this is one more argument for keeping the current notification icon design.

**Comment by dirtydancing** [comment]
This is a good opportunity to clarify the notification icon names, regardless of the design, cf. https://github.com/numixproject/numix-icon-theme/issues/474.

**Comment by wa4557** [comment]
Fine, I can live with that as well :) but then at least the notification icon should be enhanced. This one doesn't look good imo

**Comment by dirtydancing** [comment]
1) wwan icon: I actually like that one :) It is quite distinctive. Any suggestions?

Current wwan notification icon design:

![wwan](https://cloud.githubusercontent.com/assets/7164227/7421875/8607e272-ef88-11e4-86c1-508904425dd7.png)

2) ethernet icon: how about taking the one that we came up with for `devices` so far and adapt it to the notification style, like so. Should I create a pull request for that one (current one is also fine imo)?

![ethernet](https://cloud.githubusercontent.com/assets/7164227/7421959/3672cbd6-ef89-11e4-8bcf-12f97d0fd823.png)

In comparison, this is the current ethernet design (name for connected already "clarified", cf. https://github.com/numixproject/numix-icon-theme/issues/474):

![ethernet_2](https://cloud.githubusercontent.com/assets/7164227/7421737/86cc6fd0-ef87-11e4-8922-4e565476714c.png)

Actually, I would suggest to wait until the ethernet wired `device` icon has got sorted, cf. https://github.com/numixproject/numix-icon-theme/pull/468, before changing the `notification` icon, in order to possibly make these consistent.
