### ISSUE TITLE
Enhancements for usb Icon

### ISSUE THREAD

**Issue by Yankees3028** [numixproject/numix-icon-theme#479]
Hi, this Numix-Circle icon doesn't look quite as converged with the other icons. In fact (in my opinion, right now the current icon looks horrid.

Icon line: Icon=drive-removable-media

selection_010

I was told to mention this comment from a user:dirtydancing at the numix-circle forum:

This icon is not part of Numix-Circle, but rather of Numix base, which incidentally is also why it does not have a Numix-Circle design :). Please file this issue over at Numix base: https://github.com/numixproject/numix-icon-theme/issues

Please also note the related open issue numixproject/numix-icon-theme#101 and specifically this comment numixproject/numix-icon-theme#101 (comment)

Screenshot from current 48x48/devices in Numix base:

![image](https://cloud.githubusercontent.com/assets/12204992/7443282/7ceef074-f10c-11e4-9de8-dfffc2777dc7.png)

Thank you, I hope you can help!

**Comment by dirtydancing** [comment]
@Foggalong As you have classified this as `wontfix` in Numix-Circle, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/2061, I take it that this design will stay?

The specific comment I referred to is this one: https://github.com/numixproject/numix-icon-theme/issues/101#issuecomment-58883307, suggesting a differentiation between USB sticks and USB harddrives.

@Yankees3028 As you wrote that the icon name is `drive-removable-media`, if possible could you provide a screenshot with this icon and which USB device this is indicating? I am asking because there are also the icon names `drive-removable-media-usb` and `drive-harddisk-usb`.

**Comment by Foggalong** [comment]
Yeah, the USB design is here to stay for now :) the destinction between sticks and harddrives will still happen though, so I'll keep #101 open :)

**Comment by Yankees3028** [comment]
@dirtydancing I'd be more than glad to provide a screenshot, but could be more specific on what you want.

**Comment by dirtydancing** [comment]
@Yankees3028 Thanks, and sorry for any confusion caused. No screenshot needed anymore, as this issue is a `wontfix` :)
