### ISSUE TITLE
Please make use of Git Tags

### ISSUE THREAD

**Issue by sspreitzer** [numixproject/numix-icon-theme#855]
Hi

Please make use of Git Tags and tag your versions and releases.

Thank you

**Comment by palob** [comment]
Is there an automated way to do this, like every week or so?

**Comment by sspreitzer** [comment]
You can use git tag to create tags and script it with a cron job.
BUT:
When you reached a version (like 2.3.3) its recommended to tag it in git as such
eg.
```bash
$ git tag v2.3.3
$ git push origin v2.3.3
```
See also: https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by ChuckDaniels87** [comment]
Same issue: numixproject/numix-icon-theme-circle#2651. Let's talk about it in just one place.

**Comment by Foggalong** [comment]
[See reasoning here](https://github.com/numixproject/numix-icon-theme-circle/issues/1789)

**Comment by jbicha** [comment]
Could we please get git tags now?

I guess this bug was closed because "well we have Fedora packages now". (The see reasoning link above doesn't work.)

Without formal releases, there is little incentive to keep the packaging up-to-date. In Debian, I only updated numix-icon-theme once just to have a bit newer version in the coming new stable release. But I'm much more interested in updating numix-gtk-theme since it's a lot more clear when the packaged version is outdated.

I have an ugly script to try to repackage a Git snapshot. It would be a lot nicer and easier for distros to work with at least a Git tag.

I suggest you could start by tagging the current HEAD as 0.1 or whatever since that's what will [probably](https://tracker.debian.org/pkg/numix-icon-theme) be in the new Debian stable release this year.

**Comment by Foggalong** [comment]
@jbicha I'm gonna be seeting up automated buildling and tagging for circle and when I do I'll set up a similar system for this. Does monthly releases sound okay?

**Comment by jbicha** [comment]
@Foggalong monthly, annual, whatever is fine. I appreciate it!

**Comment by Foggalong** [comment]
@jbicha @sspreitzer [Tags are now used](https://github.com/numixproject/numix-icon-theme/releases/tag/17-04-05) :)
