### ISSUE TITLE
Geogebra Mimetype

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#904]
Name: application/vnd.geogebra.file
Use: Geogebra graph files
Icon: 
![screenshot_2015-12-05_20-41-22](https://cloud.githubusercontent.com/assets/5920259/11610104/94e391b0-9b90-11e5-9a61-7b3d9bbcdc2f.png)

**Comment by bil-elmoussaoui** [comment]
Need this one too :dancers:

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11610636/c4a30e1c-9b90-11e5-8ab5-c85cbe0934fd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11610637/c71f3422-9b90-11e5-9151-f987c19ba732.png)![image](https://cloud.githubusercontent.com/assets/11244067/11610638/d0b4689a-9b90-11e5-95bd-e13e5bc4ed49.png)![image](https://cloud.githubusercontent.com/assets/11244067/11610639/d832fab4-9b90-11e5-8110-8cc68a05284f.png)

**Description:** I've tried with the logo, let me know the possible design ideas of this mimetype.

**Comment by bil-elmoussaoui** [comment]
Love the first one from left :+1:

**Comment by Foggalong** [comment]
Yeah, first one from left is pretty nice :)

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11611803/5a629a7c-9bc7-11e5-9df5-ec695245460d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11611804/6015bd82-9bc7-11e5-8547-e71ee075b6f8.png)![image](https://cloud.githubusercontent.com/assets/11244067/11611830/793abd02-9bc8-11e5-8e04-8487f80bb912.png)![image](https://cloud.githubusercontent.com/assets/11244067/11611808/6c2f5740-9bc7-11e5-8739-ba08714ebd8b.png)![image](https://cloud.githubusercontent.com/assets/11244067/11611810/725db896-9bc7-11e5-977a-ecfcd21b580c.png)

Any change needed?

**Comment by Foggalong** [comment]
Well we can't tell til a pull is made :P

**Comment by wa4557** [comment]
It doesn't scale very good imo, maybe remove  one circle for 16/2/24?

**Comment by Foggalong** [comment]
I think it's already down 2 circle form 16px but yeah maybe try losing one for 22/24 too

**Comment by hlechner** [comment]
I agree, its because of the circle's size. The 24 and 16 uses a 3x3 circle what looks kind of blur even aligned.

So here the test with 4x4 circle, with of course less circles because of space:

24:
![image](https://cloud.githubusercontent.com/assets/11244067/11613726/815dde0c-9c12-11e5-8c6c-3c312c5fb7b6.png)![image](https://cloud.githubusercontent.com/assets/11244067/11613728/8bb8d1cc-9c12-11e5-902a-8aa6803f0d0f.png)
16:
![image](https://cloud.githubusercontent.com/assets/11244067/11613739/001dac0e-9c13-11e5-9154-f58fe190b1ca.png)

And also the original 24 with losing one circle:
![image](https://cloud.githubusercontent.com/assets/11244067/11613753/8201dfce-9c13-11e5-988d-ae1f03a3ddd9.png)

--

The problem with the 24 design with 3 circles with 4x4 size it looks something like ubuntu symbol.

**Comment by Foggalong** [comment]
The one with 3 for 24 is much better :+1:
